### ISSUE TITLE
Sometime error: You attempted to set the key `height` with the value `56`

### ISSUE THREAD

**Issue by longunibbo** [tuantle/react-native-search-header#31] opened 2019-02-12 14:38 UTC
Sometimes I get this error. Can you please fix it?

```
Error: Error: You attempted to set the key `height` with the value `56` on an object that is meant to be immutable and has been frozen.
```

**Comment by tuantle** [comment] 2019-02-12 17:27
Were you trying to change the style like this? 

`
<SearchHeader
  style = {{
     header: {
        height: 56
      }
   }}
/>
`

Can you post how you use the component so that I can recreate the error?

**Comment by longunibbo** [comment] 2019-02-13 02:09
```
<SearchHeader
                    ref={(searchHeader) => {
                        this.searchHeader = searchHeader;
                    }}
                    style={{
                        container: {
                            justifyContent: 'center',
                            alignItems: 'center'
                        },
                        header: {
                            height: 50,
                            width: '95%',
                            borderRadius: 25,
                            backgroundColor: '#F0F0F0'
                        },
                        suggestion: {
                            width: DEVICE_WIDTH
                        },
                    }}
                    placeholder='Search...'
                    placeholderColor='gray'
                    onClear={() => {
                        console.log(`Clearing input!`);
                    }}
                    onSearch={() => {
                        console.log('onSearch');
                    }}
                    onHide={() => this.searchHeader.show()}
                    onGetAutocompletions={async (text) => {
                        if (text) {
                            const response = await fetch(`http://suggestqueries.google.com/complete/search?client=firefox&q=${text}`, {
                                method: `get`
                            });
                            const data = await response.json();
                            return data[1];
                        } else {
                            return [];
                        }
                    }}
                />
```

This is my use of your SearchHeader. By the way, is there anyway to make SearchBar always displayed?

**Comment by tuantle** [comment] 2019-02-13 05:45
What version of this component are you using? is it 0.3.1?

And to have it always displayed, set property `persistent = { true }`

**Comment by longunibbo** [comment] 2019-02-13 06:27
I'm using this version: `"react-native-search-header": "^0.3.1",`

**Comment by tuantle** [comment] 2019-02-13 06:59
I can't reproduce this. And like you said it only happens sometime. I am guessing that this line `onHide={() => this.searchHeader.show()}` is messing with the animation? Can you replace that with `persistent = { true }` and see if that still give you error sometime.

**Comment by longunibbo** [comment] 2019-02-13 07:28
Thank you for `persistent = { true }`
About the issue, it's not always but the frequency is high, though I removed `onHide={() => this.searchHeader.show()}`
In my app, the first time I open the component with SearchHeader is ok
Later, it will crash like below

![image](https://user-images.githubusercontent.com/38639215/52694210-820f7c00-2f9b-11e9-97c1-5673d6ba6be3.png)

**Comment by tuantle** [comment] 2019-02-13 07:52
Can you try this?  Set props:
`persistent = { true }
 visibleInitially = { true }
`

And replace the `componentDidUpdate` lifecycle function with the one below.
Still not sure where the bug is, but guessing it has something to do with this component updating the animation after `componentDidUpdate`.

`
    componentDidUpdate () {
        const component = this;
        const {
            visibleInitially,
            persistent,
            enableSuggestion,
            entryAnimation
        } = component.props;
        const {
            visible,
            input,
            suggestion
        } = component.state;
        const [ animatedSearchHeaderView ] = component.lookupComponentRefs(`animated-search-header-view`);

        if (visible) {
            const [ textInput ] = component.lookupComponentRefs(`text-input`);
            if (input.focused) {
                textInput.focus();
            } else {
                textInput.blur();
            }
            if (!visibleInitially || !persistent) {
                animatedSearchHeaderView.transitionTo({
                    opacity: 1,
                    translateX: 0
                });
            }
            if (enableSuggestion) {
                const [ animatedSuggestionView ] = component.lookupComponentRefs(`animated-suggestion-view`);
                if (suggestion.visible) {
                    animatedSuggestionView.transitionTo({
                        opacity: 1,
                        translateY: 0,
                        height: DEVICE_HEIGHT / 2
                    });
                } else {
                    animatedSuggestionView.transitionTo({
                        opacity: 0,
                        translateY: DEVICE_HEIGHT,
                        height: 0
                    });
                }
            }
        } else {
            if (entryAnimation === `from-right-side`) {
                animatedSearchHeaderView.transitionTo({
                    opacity: 0,
                    translateX: DEVICE_WIDTH
                });
            } else if (entryAnimation === `from-left-side`) {
                animatedSearchHeaderView.transitionTo({
                    opacity: 0,
                    translateX: -DEVICE_WIDTH
                });
            }
        }
    }
`

**Comment by longunibbo** [comment] 2019-02-13 10:03
Thank you for your support but it seems to not be helpful. Can you have a look on my code

```
import React, {Component} from 'react';
import {Dimensions, StyleSheet, View} from 'react-native';
import SearchHeader from 'react-native-search-header';

const DEVICE_WIDTH = Dimensions.get(`window`).width;
const DEVICE_HEIGHT = Dimensions.get(`window`).height;


export default class SearchingProductScreen extends Component {

    render() {
        return (
            <View style={styles.container}>
                <SearchHeader
                    ref={(searchHeader) => {
                        this.searchHeader = searchHeader;
                    }}
                    style={{
                        container: {
                            justifyContent: 'center',
                            alignItems: 'center'
                        },
                        header: {
                            height: 50,
                            width: '95%',
                            borderRadius: 25,
                            backgroundColor: '#F0F0F0'
                        },
                        suggestion: {
                            width: DEVICE_WIDTH
                        },
                    }}
                    persistent={true}
                    visibleInitially={true}
                    placeholder='Search...'
                    placeholderColor='gray'
                    onClear={() => {
                        console.log(`Clearing input!`);
                    }}
                    onSearch={() => {
                        console.log('onSearch');
                    }}
                    onGetAutocompletions={async (text) => {
                        if (text) {
                            const response = await fetch(`http://suggestqueries.google.com/complete/search?client=firefox&q=${text}`, {
                                method: `get`
                            });
                            const data = await response.json();
                            return data[1];
                        } else {
                            return [];
                        }
                    }}
                />
            </View>
        );
    }

    componentDidUpdate() {
        const component = this;
        const {
            visibleInitially,
            persistent,
            enableSuggestion,
            entryAnimation
        } = component.props;
        const {
            visible,
            input,
            suggestion
        } = component.state;
        const [animatedSearchHeaderView] = component.lookupComponentRefs('animated-search-header-view');

        if (visible) {
            const [textInput] = component.lookupComponentRefs('text-input');
            if (input.focused) {
                textInput.focus();
            } else {
                textInput.blur();
            }
            if (!visibleInitially || !persistent) {
                animatedSearchHeaderView.transitionTo({
                    opacity: 1,
                    translateX: 0
                });
            }
            if (enableSuggestion) {
                const [animatedSuggestionView] = component.lookupComponentRefs('animated-suggestion-view');
                if (suggestion.visible) {
                    animatedSuggestionView.transitionTo({
                        opacity: 1,
                        translateY: 0,
                        height: DEVICE_HEIGHT / 2
                    });
                } else {
                    animatedSuggestionView.transitionTo({
                        opacity: 0,
                        translateY: DEVICE_HEIGHT,
                        height: 0
                    });
                }
            }
        } else {
            if (entryAnimation === 'from-right-side') {
                animatedSearchHeaderView.transitionTo({
                    opacity: 0,
                    translateX: DEVICE_WIDTH
                });
            } else if (entryAnimation === 'from-left-side') {
                animatedSearchHeaderView.transitionTo({
                    opacity: 0,
                    translateX: -DEVICE_WIDTH
                });
            }
        }
    }
}

SearchingProductScreen.navigationOptions = {
    title: 'What are you looking for?',
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white'
    },
});
```

**Comment by tuantle** [comment] 2019-02-13 15:53
No problem at all. I am glad to help. Also for the componentDidUpdate, you have to open `node_modules/react-native-search-header/search-header.js` and replace the one in there.  What this does is to turn off header view animation when both visibleInitially and persistent are true. Hoping that will fix the issue.

**Comment by longunibbo** [comment] 2019-02-13 16:06
I don't understand why if I remove these values from search-header.js, I will work
```
         height: 56,
        backgroundColor: `#fdfdfd`
```

**Comment by tuantle** [comment] 2019-02-13 16:45
Ok can you try this? Replace `search-header.js` in your `node_modules/react-native-search-header/search-header.js` with this version below.

`
'use strict'; // eslint-disable-line

import React from 'react';

import ReactNative from 'react-native'; // eslint-disable-line

import PropTypes from 'prop-types';

import { merge, clone } from 'lodash';

import { View as AnimatedView } from 'react-native-animatable';

import dismissKeyboard from 'react-native/Libraries/Utilities/dismissKeyboard';

import hideIcon from './assets/icons/hide-3x.png';
import closeIcon from './assets/icons/close-3x.png';
import historyIcon from './assets/icons/history-3x.png';
import recallIcon from './assets/icons/recall-3x.png';
import searchIcon from './assets/icons/search-3x.png';

const {
    Component
} = React;

const {
    Text,
    Image,
    View,
    FlatList,
    TextInput,
    TouchableOpacity,
    Dimensions,
    PixelRatio
} = ReactNative;

const DEVICE_WIDTH = Dimensions.get(`window`).width;
const DEVICE_HEIGHT = Dimensions.get(`window`).height;

const DEFAULT_DROP_SHADOW_STYLE = {
    shadowRadius: 2,
    shadowOpacity: 0.2,
    shadowOffset: {
        width: 0,
        height: 1
    },
    shadowColor: `#000000`
};

const DEFAULT_SEARCH_HEADER_VIEW_STYLE = {
    container: {
        ...DEFAULT_DROP_SHADOW_STYLE,
        position: `absolute`,
        alignItems: `stretch`,
        justifyContent: `flex-start`,
        zIndex: 10,
        elevation: 2,
        top: 0,
        marginBottom: 6,
        width: DEVICE_WIDTH,
        backgroundColor: `transparent`,
        overflow: `hidden`
    },
    header: {
        flexGrow: 1,
        flexDirection: `row`,
        alignItems: `center`,
        justifyContent: `space-between`,
        height: 56,
        backgroundColor: `#fdfdfd`
    },
    action: {
        flexDirection: `row`,
        alignItems: `center`,
        justifyContent: `center`,
        minWidth: 46,
        minHeight: 46,
        backgroundColor: `transparent`
    },
    suggestion: {
        ...DEFAULT_DROP_SHADOW_STYLE,
        flexShrink: 1,
        flexDirection: `column`,
        alignItems: `stretch`,
        justifyContent: `center`,
        paddingLeft: 12,
        marginVertical: 6,
        maxHeight: DEVICE_HEIGHT / 2,
        backgroundColor: `#fdfdfd`
    },
    input: {
        flex: 1,
        fontSize: PixelRatio.get() >= 3 ? 20 : 18,
        fontWeight: `400`,
        textAlign: `left`,
        marginVertical: 1,
        padding: 5,
        borderRadius: 5,
        color: `#5d5d5d`,
        backgroundColor: `transparent`
    },
    suggestionEntry: {
        flex: 1,
        fontSize: PixelRatio.get() >= 3 ? 20 : 18,
        fontWeight: `400`,
        textAlign: `left`,
        marginVertical: 3,
        paddingVertical: 3,
        marginLeft: 8,
        color: `#5d5d5d`,
        maxWidth: DEVICE_WIDTH - 92,
        backgroundColor: `transparent`
    },
    icon: {
        width: 24,
        height: 24,
        tintColor: `#5d5d5d`,
        backgroundColor: `transparent`
    }
};

const DEFAULT_ICON_IMAGE_COMPONENTS = [{
    name: `close`,
    customStyle: {},
    render: (style) => {
        return (
            <Image
                resizeMode = 'cover'
                source = { closeIcon }
                style = { style }
            />
        );
    }
}, {
    name: `hide`,
    customStyle: {},
    render: (style) => {
        return (
            <Image
                resizeMode = 'cover'
                source = { hideIcon }
                style = { style }
            />
        );
    }
}, {
    name: `history`,
    customStyle: {},
    render: (style) => {
        return (
            <Image
                resizeMode = 'cover'
                source = { historyIcon }
                style = { style }
            />
        );
    }
}, {
    name: `search`,
    customStyle: {},
    render: (style) => {
        return (
            <Image
                resizeMode = 'cover'
                source = { searchIcon }
                style = { style }
            />
        );
    }
}, {
    name: `recall`,
    customStyle: {},
    render: (style) => {
        return (
            <Image
                resizeMode = 'cover'
                source = { recallIcon }
                style = { style }
            />
        );
    }
}];

export default class SearchHeader extends Component {
    static propTypes = {
        inputColor: PropTypes.string,
        inputBgColor: PropTypes.string,
        placeholderColor: PropTypes.string,
        suggestionEntryColor: PropTypes.string,
        iconColor: PropTypes.string,
        topOffset: PropTypes.number,
        headerHeight: PropTypes.number,
        headerBgColor: PropTypes.string,
        dropShadowed: PropTypes.bool,
        visibleInitially: PropTypes.bool,
        autoFocus: PropTypes.bool,
        autoCorrect: PropTypes.bool,
        persistent: PropTypes.bool,
        enableSuggestion: PropTypes.bool,
        suggestionHistoryEntryRollOverCount: PropTypes.number,
        placeholder: PropTypes.string,
        entryAnimation: PropTypes.oneOf([ `from-left-side`, `from-right-side` ]),
        iconImageComponents: PropTypes.array,
        onClearSuggesstion: PropTypes.func,
        onGetAutocompletions: PropTypes.func,
        onClear: PropTypes.func,
        onSearch: PropTypes.func,
        onEnteringSearch: PropTypes.func,
        onFocus: PropTypes.func,
        onBlur: PropTypes.func,
        onHide: PropTypes.func,
        onShow: PropTypes.func
    }
    static defaultProps = {
        inputColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.input.color,
        inputBgColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.input.backgroundColor,
        placeholderColor: `#bdbdbd`,
        suggestionEntryColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.suggestionEntry.color,
        iconColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.icon.tintColor,
        topOffset: 24,
        headerHeight: DEFAULT_SEARCH_HEADER_VIEW_STYLE.header.height,
        headerBgColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.header.backgroundColor,
        dropShadowed: true,
        visibleInitially: false,
        autoFocus: true,
        autoCorrect: true,
        persistent: false,
        enableSuggestion: true,
        suggestionHistoryEntryRollOverCount: 16,
        placeholder: ``,
        entryAnimation: `from-left-side`,
        iconImageComponents: DEFAULT_ICON_IMAGE_COMPONENTS,
        onClearSuggesstion: () => false,
        onGetAutocompletions: () => [],
        onClear: () => null,
        onSearch: () => null,
        onEnteringSearch: () => null,
        onFocus: () => null,
        onBlur: () => null,
        onHide: () => null,
        onShow: () => null
    }
    constructor (property) {
        super(property);
        this.refCache = {};
        this.state = {
            adjustedStyle: DEFAULT_SEARCH_HEADER_VIEW_STYLE,
            customeIconImageComponents: DEFAULT_ICON_IMAGE_COMPONENTS,
            visible: false,
            input: {
                focused: false,
                value: ``,
                valueChanged: false
            },
            suggestion: {
                visible: false,
                historyEntryIndex: 0,
                historyEntryRollOverCount: 0,
                histories: [],
                autocompletes: []
            }
        };
    }
    assignComponentRef = (refName) => {
        const component = this;

        if (typeof refName !== `string`) {
            throw new Error(`ERROR: SearchHeader.assignComponentRef - Input component reference name is invalid.`);
        } else {
            const setComponentRef = function setComponentRef (componentRef) {
                component.refCache[refName] = typeof componentRef !== undefined ? componentRef : null;
            };
            return setComponentRef;
        }
    }
    lookupComponentRefs = (...refNames) => {
        const component = this;
        let componentRefs = [];

        if (refNames) {
            componentRefs = refNames.map((refName) => {
                if (typeof refName !== `string`) {
                    throw new Error(`ERROR: SearchHeader.lookupComponentRefs - Input component reference name is invalid.`);
                } else if (!component.refCache.hasOwnProperty(refName)) {
                    return null;
                } else {
                    return component.refCache[refName];
                }
            });
        } else {
            throw new Error(`ERROR: SearchHeader.lookupComponentRefs - Input component reference name array is empty.`);
        }

        return componentRefs;
    }
    _readjustStyle = (newStyle = {
        inputColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.input.color,
        inputBgColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.input.backgroundColor,
        suggestionEntryColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.suggestionEntry.color,
        iconColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.icon.tintColor,
        topOffset: 24,
        headerHeight: DEFAULT_SEARCH_HEADER_VIEW_STYLE.header.height,
        headerBgColor: DEFAULT_SEARCH_HEADER_VIEW_STYLE.header.backgroundColor,
        dropShadowed: true,
        visibleInitially: false,
        autoFocus: true,
        autoCorrect: true,
        persistent: false,
        entryAnimation: `from-left-side`
    }, prevState) => {
        const component = this;
        const {
            headerHeight,
            headerBgColor,
            iconColor,
            inputColor,
            inputBgColor,
            suggestionEntryColor,
            topOffset,
            dropShadowed,
            visibleInitially,
            persistent,
            entryAnimation,
            style
        } = newStyle;
        const {
            adjustedStyle: prevAdjustedStyle
        } = prevState;
        const adjustedStyle = merge(clone(prevAdjustedStyle), {
            container: {
                top: topOffset,
                shadowOpacity: dropShadowed ? DEFAULT_DROP_SHADOW_STYLE.shadowOpacity : 0,
                transform: [{
                    translateX: (() => {
                        if (visibleInitially || persistent) {
                            return 0;
                        } else if (!visibleInitially && entryAnimation === `from-left-side`) {
                            return -DEVICE_WIDTH;
                        } else if (!visibleInitially && entryAnimation === `from-right-side`) {
                            return DEVICE_WIDTH;
                        }
                    })()
                }]
            },
            header: {
                height: headerHeight,
                backgroundColor: headerBgColor
            },
            suggestion: {
                shadowOpacity: dropShadowed ? DEFAULT_DROP_SHADOW_STYLE.shadowOpacity : 0
            },
            input: {
                backgroundColor: inputBgColor,
                color: inputColor
            },
            suggestionEntry: {
                color: suggestionEntryColor
            },
            icon: {
                tintColor: iconColor
            }
        });

        return typeof style === `object` ? merge(adjustedStyle, style) : adjustedStyle;
    }
    isHidden = () => {
        const component = this;
        const {
            visible
        } = component.state;

        return !visible;
    }
    hide = () => {
        const component = this;
        const {
            persistent,
            onHide
        } = component.props;

        if (!persistent) {
            const [ textInput ] = component.lookupComponentRefs(`text-input`);

            if (textInput !== null) {
                textInput.clear();
                component.setState((prevState) => {
                    return {
                        visible: false,
                        input: {
                            ...prevState.input,
                            focused: false,
                            valueChanged: false
                        },
                        suggestion: {
                            ...prevState.suggestion,
                            visible: false,
                            autocompletes: []
                        }
                    };
                }, () => {
                    onHide();
                });
            }
            dismissKeyboard();
        }
    }
    show = () => {
        const component = this;
        const {
            persistent,
            onShow
        } = component.props;

        if (!persistent) {
            component.setState((prevState) => {
                return {
                    visible: true,
                    input: {
                        ...prevState.input,
                        focused: false
                    }
                };
            }, () => {
                onShow();
            });
        }
    }
    clear = () => {
        const component = this;
        const {
            onClear
        } = component.props;
        const [ textInput ] = component.lookupComponentRefs(`text-input`);

        if (textInput !== null) {
            textInput.clear();
            component.setState((prevState) => {
                return {
                    input: {
                        ...prevState.input,
                        value: ``,
                        valueChanged: true
                    },
                    suggestion: {
                        ...prevState.suggestion,
                        visible: false
                    }
                };
            }, () => {
                onClear();
            });
        }
    }
    clearSuggestion = () => {
        const component = this;

        component.setState(() => {
            return {
                suggestion: {
                    visible: false,
                    historyEntryIndex: 0,
                    historyEntryRollOverCount: 0,
                    histories: [],
                    autocompletes: []
                }
            };
        });
    }
    onFocus = () => {
        const component = this;
        const {
            onFocus
        } = component.props;

        component.setState((prevState) => {
            return {
                input: {
                    ...prevState.input,
                    focused: true
                }
            };
        }, () => {
            onFocus();
        });
    }
    onBlur = () => {
        const component = this;
        const {
            onBlur
        } = component.props;

        component.setState((prevState) => {
            return {
                input: {
                    ...prevState.input,
                    focused: false
                }
            };
        }, () => {
            onBlur();
        });
    }
    onEditting = (value) => {
        const component = this;
        const {
            onGetAutocompletions,
            onEnteringSearch
        } = component.props;

        const fetchSearchAutocompletions = async function () {
            const autocompleteTexts = await onGetAutocompletions(value);
            if (Array.isArray(autocompleteTexts) && autocompleteTexts.length) {
                component.setState((prevState) => {
                    return {
                        // suggestion: {
                        //     ...prevState.suggestion,
                        //     visible: true,
                        //     autocompletes: [
                        //         ...new Set(autocompleteTexts.filter((text) => typeof text === `string`).map((text) => text.replace(/\s/g, ``)))
                        //     ].map((text) => {
                        //         return {
                        //             historyType: false,
                        //             value: text
                        //         };
                        //     })
                        // }
                        suggestion: {
                            ...prevState.suggestion,
                            visible: true,
                            autocompletes: [
                                ...new Set(autocompleteTexts.filter((text) => typeof text === `string`))
                            ].map((text) => {
                                return {
                                    historyType: false,
                                    value: text
                                };
                            })
                        }
                    };
                });
            } else {
                component.setState((prevState) => {
                    return {
                        suggestion: {
                            ...prevState.suggestion,
                            visible: false
                        }
                    };
                });
            }
        };

        if (value !== ``) {
            fetchSearchAutocompletions();
            component.setState((prevState) => {
                return {
                    input: {
                        ...prevState.input,
                        value,
                        valueChanged: value !== prevState.input.value,
                        focused: true
                    }
                };
            });
        } else {
            component.setState((prevState) => {
                return {
                    input: {
                        ...prevState.input,
                        value: ``,
                        valueChanged: value !== prevState.input.value,
                        focused: true
                    },
                    suggestion: {
                        ...prevState.suggestion,
                        visible: false
                    }
                };
            });
        }

        onEnteringSearch({
            nativeEvent: {
                text: value
            }
        });
    }
    onSubmitEditing = (event) => {
        const component = this;
        const {
            onSearch
        } = component.props;
        const {
            suggestion
        } = component.state;
        const value = event.nativeEvent.text;

        if (value !== ``) {
            if (!suggestion.histories.some((entry) => entry.value === value)) {
                component.setState((prevState) => {
                    let {
                        historyEntryIndex,
                        historyEntryRollOverCount,
                        histories
                    } = prevState.suggestion;

                    if (historyEntryIndex === historyEntryRollOverCount) {
                        historyEntryIndex = 0;
                    }
                    if (historyEntryIndex === histories.length) {
                        histories.push({
                            historyType: true,
                            value,
                            timestamp: new Date().getTime()
                        });
                    } else if (historyEntryIndex < histories.length) {
                        histories[historyEntryIndex] = {
                            historyType: true,
                            value,
                            timestamp: new Date().getTime()
                        };
                    }
                    historyEntryIndex++;
                    histories = histories.sort((itemA, itemB) => itemB.timestamp - itemA.timestamp);

                    return {
                        suggestion: {
                            ...prevState.suggestion,
                            visible: false,
                            historyEntryIndex,
                            histories
                        }
                    };
                });
            } else {
                component.setState((prevState) => {
                    return {
                        suggestion: {
                            ...prevState.suggestion,
                            visible: false
                        }
                    };
                });
            }
            onSearch({
                nativeEvent: {
                    text: value
                }
            });
        } else {
            component.setState((prevState) => {
                return {
                    suggestion: {
                        ...prevState.suggestion,
                        visible: false
                    }
                };
            });
        }
    }
    componentDidMount () {
        const component = this;
        const {
            inputColor,
            inputBgColor,
            suggestionEntryColor,
            iconColor,
            topOffset,
            headerHeight,
            headerBgColor,
            dropShadowed,
            visibleInitially,
            autoFocus,
            autoCorrect,
            persistent,
            entryAnimation,
            iconImageComponents,
            style,
            suggestionHistoryEntryRollOverCount
        } = component.props;

        component.setState((prevState) => {
            return {
                adjustedStyle: component._readjustStyle({
                    inputColor,
                    inputBgColor,
                    suggestionEntryColor,
                    iconColor,
                    topOffset,
                    headerHeight,
                    headerBgColor,
                    dropShadowed,
                    visibleInitially,
                    autoFocus,
                    autoCorrect,
                    persistent,
                    entryAnimation,
                    style
                }, prevState),
                visible: visibleInitially || persistent,
                suggestion: {
                    ...prevState.suggestion,
                    historyEntryRollOverCount: suggestionHistoryEntryRollOverCount
                },
                customeIconImageComponents: prevState.customeIconImageComponents.map((iconImageComponent) => {
                    const matchedIconImageComponent = iconImageComponents.find((_iconImageComponent) => _iconImageComponent.name === iconImageComponent.name);
                    return matchedIconImageComponent ? merge(matchedIconImageComponent, iconImageComponent) : iconImageComponent;
                })
            };
        });
    }
    componentDidUpdate () {
        const component = this;
        const {
            visibleInitially,
            persistent,
            enableSuggestion,
            entryAnimation
        } = component.props;
        const {
            visible,
            input,
            suggestion
        } = component.state;
        const [ animatedSearchHeaderView ] = component.lookupComponentRefs(`animated-search-header-view`);

        if (visible) {
            const [ textInput ] = component.lookupComponentRefs(`text-input`);
            if (input.focused) {
                textInput.focus();
            } else {
                textInput.blur();
            }
            if (!visibleInitially || !persistent) {
                animatedSearchHeaderView.transitionTo({
                    opacity: 1,
                    translateX: 0
                });
            }
            if (enableSuggestion) {
                const [ animatedSuggestionView ] = component.lookupComponentRefs(`animated-suggestion-view`);
                if (suggestion.visible) {
                    animatedSuggestionView.transitionTo({
                        opacity: 1,
                        translateY: 0,
                        height: DEVICE_HEIGHT / 2
                    });
                } else {
                    animatedSuggestionView.transitionTo({
                        opacity: 0,
                        translateY: DEVICE_HEIGHT,
                        height: 0
                    });
                }
            }
        } else {
            if (entryAnimation === `from-right-side`) {
                animatedSearchHeaderView.transitionTo({
                    opacity: 0,
                    translateX: DEVICE_WIDTH
                });
            } else if (entryAnimation === `from-left-side`) {
                animatedSearchHeaderView.transitionTo({
                    opacity: 0,
                    translateX: -DEVICE_WIDTH
                });
            }
        }
    }
    componentDidUnMount () {
        const component = this;

        component.refCache = {};
    }
    renderInput () {
        const component = this;
        const {
            placeholderColor,
            autoFocus,
            autoCorrect,
            persistent,
            placeholder,
            onSearch
        } = component.props;

        const {
            adjustedStyle,
            customeIconImageComponents,
            input
        } = component.state;

        return (
            <View style = { adjustedStyle.header }>
                <View style = { adjustedStyle.action }>
                    {
                        !persistent ? <TouchableOpacity onPress = {() => {
                            component.hide();
                        }}>
                            {
                                customeIconImageComponents.filter((iconImageComponent) => iconImageComponent.name === `hide`).map((iconImageComponent) => {
                                    return iconImageComponent.render([
                                        adjustedStyle.icon,
                                        iconImageComponent.customStyle
                                    ]);
                                })[0]
                            }
                        </TouchableOpacity> : <TouchableOpacity onPress = {() => {
                            onSearch({
                                nativeEvent: {
                                    text: input.value
                                }
                            });
                        }}>
                            {
                                customeIconImageComponents.filter((iconImageComponent) => iconImageComponent.name === `search`).map((iconImageComponent) => {
                                    return iconImageComponent.render([
                                        adjustedStyle.icon,
                                        iconImageComponent.customStyle
                                    ]);
                                })[0]
                            }
                        </TouchableOpacity>
                    }
                </View>
                <TextInput
                    ref = { component.assignComponentRef(`text-input`) }
                    autoFocus = { autoFocus }
                    autoCorrect = { autoCorrect }
                    returnKeyType = 'search'
                    underlineColorAndroid = 'transparent'
                    placeholder = { placeholder }
                    placeholderTextColor = { placeholderColor }
                    value = { input.value }
                    style = { adjustedStyle.input }
                    onFocus = { component.onFocus }
                    onBlur = { component.onBlur }
                    onChangeText = { component.onEditting }
                    onSubmitEditing = { component.onSubmitEditing }
                />
                {
                    input.value === `` ? <View style = { adjustedStyle.action } /> : <View style = { adjustedStyle.action }>
                        <TouchableOpacity onPress = {() => {
                            component.clear();
                        }}>
                            {
                                customeIconImageComponents.filter((iconImageComponent) => iconImageComponent.name === `close`).map((iconImageComponent) => {
                                    return iconImageComponent.render([
                                        adjustedStyle.icon,
                                        iconImageComponent.customStyle
                                    ]);
                                })[0]
                            }
                        </TouchableOpacity>
                    </View>
                }
            </View>
        );
    }
    renderSuggestions () {
        const component = this;
        const {
            onEnteringSearch,
            onSearch
        } = component.props;
        const {
            adjustedStyle,
            customeIconImageComponents,
            input,
            suggestion
        } = component.state;
        // let suggestionEntries = suggestion.histories.concat(suggestion.autocompletes);
        //
        // suggestionEntries = suggestionEntries.filter((entry) => {
        //     return entry.value !== `` && input.value !== `` && entry.value.toLowerCase().includes(input.value.toLowerCase());
        // }).map((entry, index) => {
        //     return {
        //         key: `${index}`,
        //         ...entry
        //     };
        // });

        let suggestionEntries = suggestion.histories.filter((entry) => {
            return entry.value.toLowerCase().charAt(0) === input.value.toLowerCase().charAt(0);
        }).concat(suggestion.autocompletes);

        suggestionEntries = suggestionEntries.map((entry, index) => {
            return {
                key: `${index}`,
                ...entry
            };
        });

        return (
            <AnimatedView
                ref = { component.assignComponentRef(`animated-suggestion-view`) }
                duration = { 300 }
                useNativeDriver = { false }
                style = { adjustedStyle.suggestion }
            >
                <FlatList
                    data = { suggestionEntries }
                    renderItem = {(listData) => {
                        const entry = listData.item;

                        return (
                            <TouchableOpacity
                                key = { listData.key }
                                onPress = {() => {
                                    const [ textInput ] = component.lookupComponentRefs(`text-input`);
                                    textInput.setNativeProps({
                                        text: entry.value
                                    });

                                    component.setState((prevState) => {
                                        return {
                                            input: {
                                                ...prevState.input,
                                                value: entry.value,
                                                valueChanged: prevState.input.value !== entry.value,
                                                focused: false
                                            },
                                            suggestion: {
                                                ...prevState.suggestion,
                                                visible: false,
                                                autocompletes: []
                                            }
                                        };
                                    });

                                    onEnteringSearch({
                                        nativeEvent: {
                                            text: entry.value
                                        }
                                    });
                                    onSearch({
                                        nativeEvent: {
                                            text: entry.value
                                        }
                                    });
                                }}>
                                <View style = {{
                                    flexDirection: `row`,
                                    justifyContent: `center`,
                                    alignItems: `center`,
                                    backgroundColor: `transparent`
                                }}>
                                    {
                                        customeIconImageComponents.filter((iconImageComponent) => entry.historyType ? iconImageComponent.name === `history` : iconImageComponent.name === `search`).map((iconImageComponent) => {
                                            return iconImageComponent.render([
                                                adjustedStyle.icon,
                                                iconImageComponent.customStyle
                                            ]);
                                        })[0]
                                    }
                                    <Text
                                        numberOfLines = { 1 }
                                        ellipsizeMode = 'tail'
                                        style = { adjustedStyle.suggestionEntry }
                                    >{ entry.value }</Text>
                                    <View style = {{
                                        flexDirection: `row`,
                                        alignItems: `center`,
                                        justifyContent: `center`,
                                        minWidth: 46,
                                        minHeight: 46,
                                        backgroundColor: `transparent`
                                    }}>
                                        <TouchableOpacity onPress = {() => {
                                            const [ textInput ] = component.lookupComponentRefs(`text-input`);
                                            textInput.setNativeProps({
                                                text: entry.value
                                            });

                                            component.setState((prevState) => {
                                                return {
                                                    input: {
                                                        ...prevState.input,
                                                        value: entry.value,
                                                        valueChanged: prevState.input.value !== entry.value
                                                    }
                                                };
                                            });
                                        }}>
                                            {
                                                customeIconImageComponents.filter((iconImageComponent) => iconImageComponent.name === `recall`).map((iconImageComponent) => {
                                                    return iconImageComponent.render([
                                                        adjustedStyle.icon,
                                                        iconImageComponent.customStyle
                                                    ]);
                                                })[0]
                                            }
                                        </TouchableOpacity>
                                    </View>
                                </View>
                            </TouchableOpacity>
                        );
                    }}
                    style = {{
                        flexDirection: `column`,
                        backgroundColor: `transparent`
                    }}
                />
            </AnimatedView>
        );
    }
    render () {
        const component = this;
        const {
            enableSuggestion
        } = component.props;
        const {
            visible,
            adjustedStyle
        } = component.state;

        return (
            <AnimatedView
                ref = { component.assignComponentRef(`animated-search-header-view`) }
                style = { adjustedStyle.container }
                duration = { 300 }
                useNativeDriver = { true }
                onStartShouldSetResponder = {() => {
                    dismissKeyboard();
                }}
            >
                {
                    !visible ? null : component.renderInput()
                }
                {
                    !enableSuggestion ? null : component.renderSuggestions()
                }
            </AnimatedView>
        );
    }
}
`

**Comment by shiftrtech** [comment] 2019-02-16 21:26
This is happening to me when i show the searchHeader, and go to another screen and later come back to first screen (the one with the searchHeader), i try this but doesnt works:

`
componentWillUnmount() {
    this.searchHeader.clear();
    this.searchHeader.hide();
  }

`

**Comment by shiftrtech** [comment] 2019-02-16 21:33
@tuantle, can you please make a new branch with this so i can get upgrade the package and test, thanks

**Comment by tuantle** [comment] 2019-02-18 00:52
Ok, I will try and fix this issue and put the code in a develop branch for you to test it out and see if I correctly fix it.

**Comment by longunibbo** [comment] 2019-02-23 16:15
@tuantle I'm sorry for asking again. Did you manage to fix this issue? I like your searchheader lib but I'm still running in this issue

**Comment by tuantle** [comment] 2019-02-23 17:42
I am abit busy with other stuff but will post a fix in a new develop branch soon to see if the issue is resolve. Also i am testing this component when using with react navigation.

**Comment by tuantle** [comment] 2019-02-24 02:00
`npm install npm install https://github.com/tuantle/react-native-search-header.git#develop`

Try this version. I removed loads dependencies. Cleanup animation code and moved some of the animation out go componentDidMount. Don't know if this fix the main issue but try it out.

**Comment by longunibbo** [comment] 2019-03-13 02:48
@tuantle I've been using your fix for a couple of weeks, it seems that it works well now. In your master release, was this fix included? If already, I will use your latest version & you can close this issue. Thank you very much for your help & beautiful library

**Comment by tuantle** [comment] 2019-03-13 19:53
I merged the develop branch with master and nom published. I also update the default styling a bit to make it looks more consistent.

**Closed** 2019-03-29 23:50 UTC
