### ISSUE TITLE
Transform Error 

### ISSUE THREAD

**Issue by jpca999** [tuantle/react-native-search-header#10] opened 2017-11-11 21:14 UTC
![image](https://user-images.githubusercontent.com/1026325/32693577-5349680e-c6fb-11e7-8e49-0ef6cdc288f4.png)

import React from 'react';
import { StyleSheet, Text, View, Dimensions } from 'react-native';

import SearchHeader from 'react-native-search-header';

const DEVICE_WIDTH = Dimensions.get(`window`).width;

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'center',
      backgroundColor: '#f5fcff'
  },
  status: {
      zIndex: 10,
      elevation: 2,
      width: DEVICE_WIDTH,
      height: 21,
      backgroundColor: '#0097a7'
  },
  header: {
      justifyContent: 'center',
      alignItems: 'center',
      width: DEVICE_WIDTH,
      height: 56,
      marginBottom: 6,
      backgroundColor: '#00bcd4'
  },
  label: {
      flexGrow: 1,
      fontSize: 20,
      fontWeight: `600`,
      textAlign: `left`,
      marginVertical: 8,
      paddingVertical: 3,
      color: `#f5fcff`,
      backgroundColor: `transparent`
  },
  button: {
      justifyContent: 'center',
      alignItems: 'center',
      width: 130,
      height: 40,
      marginTop: 40,
      borderRadius: 2,
      backgroundColor: `#ff5722`
  }
});

**Comment by tuantle** [comment] 2017-11-12 19:11
Are you using this package with the latest react native version 0.50.3?  Looks like a babelrc issue.

**Comment by jvandijk** [comment] 2017-11-22 12:37
I'm facing this issue as well while my dependencies are perfectly aligned. Only way I could solve it is by adding `babel-preset-react` and `babel-preset-env` to the main project which should of course not be necessary.

**Comment by tuantle** [comment] 2017-11-23 19:07
I'll take a look and fix this issue in the next update. Thanks.

**Comment by jvandijk** [comment] 2017-11-27 10:50
@tuantle thanks for the changes, I can confirm that the transform error is gone..... BUT... your deep merge introduction is failing! You cannot override the styles at the moment.

**Comment by jvandijk** [comment] 2017-11-27 19:42
Thanks @tuantle you can close this issue in my opinion.

**Closed** 2017-12-05 07:37 UTC
